// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace FileNova.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Documento", b =>
                {
                    b.Property<int>("Id_Documento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_documento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Documento"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("Fecha_Modificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("Fecha_Subida")
                        .HasColumnType("datetime2");

                    b.Property<string>("Id_Usuario")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ruta");

                    b.Property<float>("Tamaño_KB")
                        .HasColumnType("real");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Documento");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("Entities.Models.Permiso", b =>
                {
                    b.Property<int>("Id_Permiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Permiso"));

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<bool>("Heredado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Selected")
                        .HasColumnType("bit");

                    b.HasKey("Id_Permiso");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Permisos", (string)null);

                    b.HasData(
                        new
                        {
                            Id_Permiso = 1,
                            Disabled = false,
                            Heredado = false,
                            Nombre = "DOCUMENTOS_VER",
                            Selected = false
                        },
                        new
                        {
                            Id_Permiso = 2,
                            Disabled = false,
                            Heredado = false,
                            Nombre = "DOCUMENTOS_CREAR",
                            Selected = false
                        },
                        new
                        {
                            Id_Permiso = 3,
                            Disabled = false,
                            Heredado = false,
                            Nombre = "DOCUMENTOS_EDITAR",
                            Selected = false
                        },
                        new
                        {
                            Id_Permiso = 4,
                            Disabled = false,
                            Heredado = false,
                            Nombre = "DOCUMENTOS_ELIMINAR",
                            Selected = false
                        },
                        new
                        {
                            Id_Permiso = 5,
                            Disabled = false,
                            Heredado = false,
                            Nombre = "ROLES_ADMIN",
                            Selected = false
                        });
                });

            modelBuilder.Entity("Entities.Models.Rol_Permiso", b =>
                {
                    b.Property<string>("Id_Rol")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id_Permiso")
                        .HasColumnType("int");

                    b.HasKey("Id_Rol", "Id_Permiso");

                    b.HasIndex("Id_Permiso");

                    b.HasIndex("Id_Rol", "Id_Permiso")
                        .IsUnique();

                    b.ToTable("Rol_Permisos", (string)null);

                    b.HasData(
                        new
                        {
                            Id_Rol = "562419f5-eed1-473b-bcc1-9f2dbab182b4",
                            Id_Permiso = 1
                        },
                        new
                        {
                            Id_Rol = "562419f5-eed1-473b-bcc1-9f2dbab182b4",
                            Id_Permiso = 2
                        },
                        new
                        {
                            Id_Rol = "562419f5-eed1-473b-bcc1-9f2dbab182b4",
                            Id_Permiso = 3
                        },
                        new
                        {
                            Id_Rol = "562419f5-eed1-473b-bcc1-9f2dbab182b4",
                            Id_Permiso = 4
                        },
                        new
                        {
                            Id_Rol = "562419f5-eed1-473b-bcc1-9f2dbab182b4",
                            Id_Permiso = 5
                        },
                        new
                        {
                            Id_Rol = "d12540b0-6de7-48dd-befa-066de9d3a6a0",
                            Id_Permiso = 1
                        });
                });

            modelBuilder.Entity("Entities.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("PermisoId_Permiso")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.HasIndex("PermisoId_Permiso");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "562419f5-eed1-473b-bcc1-9f2dbab182b4",
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = "d12540b0-6de7-48dd-befa-066de9d3a6a0",
                            Name = "Cliente",
                            NormalizedName = "CLIENTE"
                        });
                });

            modelBuilder.Entity("Entities.Models.Solicitud", b =>
                {
                    b.Property<int>("Id_Solicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_solicitud");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Solicitud"));

                    b.Property<string>("Detalles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha_Solicitud")
                        .HasColumnType("datetime2");

                    b.Property<string>("Id_Usuario")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Nombre_Solicitud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo_Solicitud")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Solicitud");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("Solicitudes");

                    b.HasData(
                        new
                        {
                            Id_Solicitud = 1,
                            Detalles = "Solicitud para obtener acceso a documentos confidenciales.",
                            Estado = "Pendiente",
                            Fecha_Solicitud = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Usuario = "1",
                            Tipo_Solicitud = "Acceso a Documentos"
                        });
                });

            modelBuilder.Entity("Entities.Models.Trazabilidad_Documento", b =>
                {
                    b.Property<int>("Id_Trazabilidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_trazabilidad_documento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Trazabilidad"));

                    b.Property<string>("Accion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha_Cambio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Documento")
                        .HasColumnType("int")
                        .HasColumnName("id_documento");

                    b.Property<string>("Id_Usuario")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Ruta_Antigua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ruta_Nueva")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Trazabilidad");

                    b.HasIndex("Id_Documento");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("Trazabilidad_Documentos");
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshTokken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            Apellido = "Sistema",
                            ConcurrencyStamp = "22222222-2222-2222-2222-222222222222",
                            Email = "admin@test.com",
                            EmailConfirmed = true,
                            Estado = 1,
                            FechaCreacion = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            MustChangePassword = true,
                            Nombre = "Admin",
                            NormalizedEmail = "ADMIN@TEST.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEBGZiSMC2XDHccsUuRCJdG0VuDXu6I7CTGDK4JVO3oX11hZ+dOcdc1TsntsHaPwjAQ==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "11111111-1111-1111-1111-111111111111",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Entities.Models.User_Permiso", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id_Permiso")
                        .HasColumnType("int");

                    b.HasKey("UserId", "Id_Permiso");

                    b.HasIndex("Id_Permiso");

                    b.ToTable("user_Permisos");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RoleId = "562419f5-eed1-473b-bcc1-9f2dbab182b4"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Documento", b =>
                {
                    b.HasOne("Entities.Models.User", "User")
                        .WithMany("Documentos")
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Models.Rol_Permiso", b =>
                {
                    b.HasOne("Entities.Models.Permiso", "Permiso")
                        .WithMany("Rol_Permisos")
                        .HasForeignKey("Id_Permiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Role", "Role")
                        .WithMany("Rol_Permisos")
                        .HasForeignKey("Id_Rol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Entities.Models.Role", b =>
                {
                    b.HasOne("Entities.Models.Permiso", null)
                        .WithMany("Roles")
                        .HasForeignKey("PermisoId_Permiso");
                });

            modelBuilder.Entity("Entities.Models.Solicitud", b =>
                {
                    b.HasOne("Entities.Models.User", "User")
                        .WithMany("Solicitudes")
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Models.Trazabilidad_Documento", b =>
                {
                    b.HasOne("Entities.Models.Documento", "Documento")
                        .WithMany("Trazabilidad_Documentos")
                        .HasForeignKey("Id_Documento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.User", "User")
                        .WithMany("Trazabilidad_Documentos")
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Documento");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Models.User_Permiso", b =>
                {
                    b.HasOne("Entities.Models.Permiso", "Permiso")
                        .WithMany("User_Permisos")
                        .HasForeignKey("Id_Permiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.User", "User")
                        .WithMany("User_Permisos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Entities.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Entities.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Documento", b =>
                {
                    b.Navigation("Trazabilidad_Documentos");
                });

            modelBuilder.Entity("Entities.Models.Permiso", b =>
                {
                    b.Navigation("Rol_Permisos");

                    b.Navigation("Roles");

                    b.Navigation("User_Permisos");
                });

            modelBuilder.Entity("Entities.Models.Role", b =>
                {
                    b.Navigation("Rol_Permisos");
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("Solicitudes");

                    b.Navigation("Trazabilidad_Documentos");

                    b.Navigation("User_Permisos");
                });
#pragma warning restore 612, 618
        }
    }
}
